### PR TITLE
[MINOR] Support specify timeout for AM waiting for client signal stop

### PR DESCRIPTION
**Pull request by zuston**
### Why
In once loop of `monitorApplication` method, when costing too much time over 15s , AM will finished, not waiting TonY client stop signal.
So AM rpc service will closed. But TonY client will call updateTaskInfos method, it will cause exception.

I think it's necessary to allow specify AM waiting timeout, because we extend the ClusterSubmmitter to support `TaskUpdateListener`, which may cost too much time in `monitorApplication` once loop.

### CODE REVIEW

**Comment by zuston** [comment]
@oliverhu Please review it. Thanks.

**Comment by oliverhu** [comment]
@zuston please check the tests failures first..

**Comment by oliverhu** [comment]
pls resolve the conflicts

**Comment by zuston** [comment]
> @zuston please check the tests failures first..
Sorry, CI test cost too much time. I sometimes forget checking its status.

> pls resolve the conflicts
OK.

**Review by oliverhu — APPROVED** [review]

**Pull request merged**
