### PR TITLE
Evaluator should be standalone with training cluster in TF

### PR DESCRIPTION
**Pull request by zuston**

### CODE REVIEW

**Comment by zuston** [comment]
### Additional instructions
The conf of the PSS in TF estimator API is inconsistent with the TF2.4 single-client PSS. It makes me confused.

Estimator Api doc: https://github.com/tensorflow/estimator/blob/781c0d30c6bf100aa174591dd97cb70fc39d294d/tensorflow_estimator/python/estimator/run_config.py#L440

Single-client PSS doc:
https://www.tensorflow.org/tutorials/distribute/parameter_server_training#set_%E2%80%9Ctf_config%E2%80%9D_environment_variable.
Attach latest developer note: https://github.com/tensorflow/tensorflow/issues/46169#issuecomment-781877716

Now in this PR, it runs OK using the estimator api TF_CONFIG wherever in estimator and TF2.x single-client PSS.

**Comment by zuston** [comment]
Please check it~ @oliverhu 
Thanks. ~~

**Comment by oliverhu** [comment]
Thanks for the PR @zuston , we need to take a closer look at the v2 of PS strategy in TF 2.4 first

**Comment by zuston** [comment]
Any update on it ?

**Comment by oliverhu** [comment]
looks good @zuston can you resolve the conflicts?

**Comment by zuston** [comment]
Of course

**Review by oliverhu — APPROVED** [review]

**Pull request merged**
