### PR TITLE
Fast fail when container launch failed

### PR DESCRIPTION
**Pull request by zuston**
Fast fail when container launch failed and container task is not in `tony.application.stop.on.failure.jobtypes`

### Why
This PR is to solve a corner case, which happend in launching container failed. And this failed container is not in `tony.application.stop.on.failure.jobtypes`. 
If not, it will hang util AM reaching `registrationTimeoutMs`.

### CODE REVIEW

**Comment by zuston** [comment]
@oliverhu Please check it. Thanks

**Review by oliverhu — APPROVED** [review]

**Comment by oliverhu** [comment]
@zuston please fix the unit tests..

**Comment by zuston** [comment]
> @zuston please fix the unit tests..

OK. I will fix it later.

**Comment by oliverhu** [comment]
@zuston  could you check `com.linkedin.tony.TestTonyE2E.testTonyAMSchedulerShouldPass` test? it seems to keep failing in master

**Pull request merged**
