### PR TITLE
1_Tony AM returns FAILED status when a non-chief worker fails

### PR DESCRIPTION
**Pull request by pdtran3k6**
Fix for https://github.com/linkedin/TonY/issues/84.

### CODE REVIEW

**Comment by pdtran3k6** [comment]
In order to test this, we need to make several fundamental changes to `TonyApplicationMaster`. I think we should discuss this offline.

**Comment by oliverhu** [comment]
Talked offline, we should refactor the `monitor()` function a bit.

**Comment by erwa** [comment]
I think this is testable even with our existing code. To trigger the

```
      if (session.isTrainingFinished()) {
        LOG.info("Training has finished.");
        return session.getFinalStatus() == FinalApplicationStatus.SUCCEEDED;
      }	
```

block, create a TonY job with 2 workers and have the Python script exit 1 if it's worker 0 and run forever if it's not worker 0. When worker 0 finishes, `trainingFinished` will be set to `true` and the above code should trigger. Check that `false` is returned.

I think you might need to refactor `TonyApplicationMaster.main()` though. Right now, there's no easy way to inspect the value of `succeeded`. But you could get access to it by refactoring `main()` to:

```
public static void main(...) {
  boolean succeeded = run(args);
    if (succeeded) {
      LOG.info("Application Master completed successfully. exiting");
      System.exit(0);
    } else {
      LOG.info("Application Master failed. exiting");
      System.exit(-1);
    }
}
```

and move the rest of the code into `run()`. Then you should be able to directly call `run()` in your test and inspect the return value.

**Comment by oliverhu** [comment]
@pdtran3k6 it would be easier to read if you have a .diff to indicate what is removed and what is added.

**Comment by pdtran3k6** [comment]
https://gist.github.com/pdtran3k6/0cd3eef0e49958dac1fa778f41b22138

**Comment by pdtran3k6** [comment]
> @pdtran3k6 it would be easier to read if you have a .diff to indicate what is removed and what is added.

https://gist.github.com/pdtran3k6/0cd3eef0e49958dac1fa778f41b22138

**Comment by erwa** [comment]
> https://gist.github.com/pdtran3k6/0cd3eef0e49958dac1fa778f41b22138

Left some comments in there but overall looks good.

**Comment by pdtran3k6** [comment]
Discussed offline with @oliverhu, we think that `runTonyAM` should be refactored to `run` and it shouldn't be static in `TonyApplicationMaster`.

**Pull request merged**
