### PR TITLE
Fix #284. Token for application rpc should support IP service name.

### LINKED ISSUE #284: Token for application rpc should support IP service name
The token generated in ApplicationMaster.prepare() uses hostname as token's service:

```
// create token for application RPC server
  Token<? extends TokenIdentifier> tensorflowClusterToken = new Token<>(identifier, secretManager);
  tensorflowClusterToken.setService(new Text(amHostPort));
  UserGroupInformation.getCurrentUser().addToken(tensorflowClusterToken);
```

The token's service name should be specified with the configuration of hadoop.security.token.service.use_ip

### PR DESCRIPTION
**Pull request by yuanzac**

### CODE REVIEW

**Comment by erwa** [comment]
Hi @yuanzac , thanks for the contribution! I haven't looked closely at your changes yet, but I see 9 tests failed in the Travis CI build. Can you take a look?: https://travis-ci.org/linkedin/TonY/builds/532813229

**Comment by yuanzac** [comment]
image

**Comment by yuanzac** [comment]
I run "./gradlew build" and all tests were passed locally. Just rebase code and submit it again.

**Comment by erwa** [comment]
Looking at https://travis-ci.org/linkedin/TonY/builds/533229154, it seems like the following 9 tests failed:

* TestTonyE2E.testTonyResourcesFlag
* TestTonyE2E.testTonyClientCallbackHandler
* TestTonyE2E.testTensorBoardPortSetOnlyOnChiefWorker
* TestTonyE2E.testTaskCompletionNotificationDelayed
* TestTonyE2E.testSingleNodeTrainingShouldPass
* TestTonyE2E.testPSWorkerTrainingShouldPass
* TestTonyE2E.testPSWorkerTrainingPyTorchShouldPass
* TestTonyE2E.testPSSkewedWorkerTrainingShouldPass
* TestTonyE2E.testNullAMRpcClient

**Comment by yuanzac** [comment]
image

**Comment by yuanzac** [comment]
E2E tests are passed when builds locally. Not quite sure about the root causes. @erwa Can you help to look at it? Or test in your local env?

**Comment by erwa** [comment]
Ok, I will try to run on my machine to see if I can reproduce it. If not, I'll check if it's an issue with the Travis CI setup.

**Comment by yuanzac** [comment]
@erwa , Any finding? Any info you need, feel free to let me know~

**Comment by erwa** [comment]
I was able to repro a test failure locally:
```
./gradlew :tony-core:test --tests *TestTonyE2E.testTonyResourcesFlag
```

Looking in `target/MiniTonY/...`, in the worker container logs, I see
```
2019-05-20 06:52:10 FATAL TaskExecutor:184 - Task command is empty. Please set tony.application.[jobtype].command or pass --executes in command line
```

This looks related to #290.

Can you rebase on `master` and update your PR?

**Comment by erwa** [comment]
I think one issue may be that the `tony-core/out/libs` directory is not getting cleaned up and refreshed. Can you update the `.travis.yml` and add `clean` to the `script` line? So:

```
script: "./gradlew clean check --stacktrace --info"
```

**Comment by yuanzac** [comment]
@erwa 
Thanks a lot for your comments. I'll update the pr shortly.

**Comment by erwa** [comment]
Hmm, someone the CI tests still didn't pass even with `clean`. I'll continue investigating.

**Comment by oliverhu** [comment]
Failing due to

``` 2019-05-24 13:42:00 INFO  TaskExecutor:100 - TaskExecutor is running..
2019-05-24 13:42:00 INFO  TaskExecutor:177 - Executor is running task ps 0
2019-05-24 13:42:00 ERROR TaskExecutor:193 - Task command is empty. Please set tony.application.[jobtype].command or pass --executes in command line
```
Seems to be in conflict with #290

**Comment by oliverhu** [comment]
Created #298  to solve this .. @yuanzac  @erwa

**Pull request closed without merging**
