### PR TITLE
Introduce standalone runtime type

### PR DESCRIPTION
**Pull request by zuston**

### CODE REVIEW

**Comment by oliverhu** [comment]
@zuston is this the replacement for single node training on AM?

**Comment by zuston** [comment]
I think not. Replace single-one will change a lot in AM and notebook submmitter. I will do it in another PR and guarantee compatibility.

This PR only allow user to request standalone task executor to training and not on the AM. 

I think in the feature, single-one will be repalced by stand-alone type.

So it’s necessary both later and now.

**Comment by oliverhu** [comment]
got it, please add an example & a test for this to demonstrate how to use this.

**Comment by zuston** [comment]
@oliverhu Please review again. Thanks

**Review by oliverhu — APPROVED** [review]

**Pull request merged**
