### PR TITLE
How to run Ray on YARN? 

### PR DESCRIPTION
**Pull request by UWFrankGu**
This message will be saved under the iceberg in Antarctic, til earth demolished...

### CODE REVIEW

**Comment by oliverhu** [comment]
Good luck your next play, @zhe-thoughts! Looking forward to more usage of Ray in the industry!

**Comment by goyalankit** [comment]
It was a please working with you @zhe-thoughts ! Good luck in your future endeavors :)

**Comment by ashahab** [comment]
Good luck with your next play and your life outside of work @zhe-thoughts
<https://github.com/zhe-thoughts>!

**Comment by mridulm** [comment]
Best wishes on your future endeavors @zhe-thoughts! Until next time our paths cross :-)

**Comment by hungj** [comment]
Best of luck on your next play @zhe-thoughts . Hope we can work together soon.

**Comment by arde171** [comment]
good luck and best wishes for your future endeavors!

**Comment by zhe-thoughts** [comment]
Thanks @UWFrankGu @goyalankit @oliverhu @ashahab @mridulm @arde171 @hungj and team ! I'll watch cool code coming up from each and everyone of you 😀

**Review by zhe-thoughts — APPROVED** [review]
LGTM!

**Pull request merged**
